# Generated by Django 4.0.5 on 2022-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schleplist', '0002_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
