# Generated by Django 4.0.6 on 2022-07-17 05:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schleplist', '0003_bookmark_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cloud_profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
