# Generated by Django 4.0.3 on 2022-04-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
